server:
  port: 9002
spring:
  application:
    name: tensquare-recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.224.129:3306/tensquare_recruit?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
##&serverTimezone=UTC