server:
  port: 9004
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_article?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
#  redis:
#    host: 127.0.0.1
##&serverTimezone=UTC